# Generated by Django 5.1.5 on 2025-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('choix_1', models.CharField(max_length=200)),
                ('choix_2', models.CharField(max_length=200)),
                ('choix_3', models.CharField(max_length=200)),
                ('choix_4', models.CharField(max_length=200)),
                ('bonne_reponse', models.CharField(max_length=200)),
                ('explication', models.TextField()),
            ],
        ),
    ]
